import { Upgrade } from '../upgrade/upgrade.model';

export const UPGRADES: Upgrade[] = [
  // Самолет
  {
    group: 'plane',
    icon: 'fa-solid fa-shuttle-space', // fa-solid fa-plane
    name: 'Планер',
    description:
      'Маневренность. Незаметность не включена в планер, т.к. подразумевается, что самолет стал маневреннее с тем же коэффициентом незаметности',
    tier: 1,
    price: 50,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-plane-arrival',
    name: 'Автопилот',
    description:
      'Возможность завершения миссии при нахождении в дружественном воздушном пространстве при отсутствии повреждений и статуса обнаруженного',
    tier: 1,
    price: 75,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-weight-hanging',
    name: 'Конструкция',
    description:
      'За счет более обширного применения титановых сплавов и композитных материалов снижается масса самолета, из-за чего возрастает дальность полета и маневренность',
    tier: 1,
    price: 100,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-paint-roller', // fa-solid fa-droplet
    name: 'Покрытие',
    description: 'Незаметность - уменьшение ЭПР',
    tier: 2,
    price: 125,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-display',
    name: 'Кабина',
    description:
      'Замена аналоговых приборов на LCD дисплеи с более продвинутым функционалом. Индикатор незаметности',
    tier: 2,
    price: 150,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-sitemap',
    name: 'Компоновка внутренних отсеков',
    description: 'Возможность устанавливать дополнительное вооружение',
    tier: 2,
    price: 175,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-fire-flame-simple', // fa-solid fa-plane-engines
    name: 'Двигатели',
    description:
      'Увеличение тяговооруженности и скорости, уменьшение расхода топлива',
    tier: 3,
    price: 200,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-radar',
    name: 'РЛС',
    description: 'ФАР - дальность обнаружения цели, незаметность',
    tier: 3,
    price: 225,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-satellite',
    name: 'ДРЛО',
    description: '',
    tier: 3,
    price: 250,
  },
  // Вооружение
  // США
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-volcano',
    name: 'M61 Vulcan',
    description: 'Пушка',
    tier: 1,
    price: 50,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-bomb',
    name: 'Mark 83',
    description: 'Бомба',
    tier: 1,
    price: 75,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-wind',
    name: 'AIM-9 Sidewinder',
    description: 'Ракета "воздух-воздух" малой дальности',
    tier: 1,
    price: 100,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-person-walking',
    name: 'AGM-65 Maverick',
    description: 'Ракета "воздух-поверхность"',
    tier: 2,
    price: 125,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-bird', // fa-dove
    name: 'AIM-7 Sparrow',
    description: 'Ракета "воздух-воздух" средней дальности',
    tier: 2,
    price: 150,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-water',
    name: 'AGM-84 Harpoon',
    description: 'Противокорабельная ракета',
    tier: 2,
    price: 175,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-brands fa-phoenix-framework',
    name: 'AIM-54 Phoenix',
    description: 'Ракета "воздух-воздух" большой дальности',
    tier: 3,
    price: 200,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-satellite-dish',
    name: 'AGM-88 HARM',
    description: 'Противорадиолокационная ракета',
    tier: 3,
    price: 225,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-radiation',
    name: 'B83',
    description: 'Атомная бомба',
    tier: 3,
    price: 250,
  },
  // СССР
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-cannon',
    name: 'ГШ-30-1',
    description: 'Пушка',
    tier: 1,
    price: 50,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-bomb',
    name: 'ФАБ-500',
    description: 'Бомба',
    tier: 1,
    price: 75,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-bow-arrow',
    name: 'Р-73 (AA-11 Archer)',
    description: 'Ракета "воздух-воздух" малой дальности',
    tier: 1,
    price: 100,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-anchor',
    name: 'Х-29 (AS-14 Kedge)',
    description: 'Ракета "воздух-поверхность"',
    tier: 2,
    price: 125,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-snake',
    name: 'Р-77 (AA-12 Adder)',
    description: 'Ракета "воздух-воздух" средней дальности',
    tier: 2,
    price: 150,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-water',
    name: 'Х-31А (AS-17 Krypton)',
    description: 'Противокорабельная ракета',
    tier: 2,
    price: 175,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-face-smile-halo',
    name: 'Р-33 (AA-9 Amos)',
    description: 'Ракета "воздух-воздух" большой дальности',
    tier: 3,
    price: 200,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-satellite-dish',
    name: 'Х-31П (AS-17 Krypton)',
    description: 'Противорадиолокационная ракета',
    tier: 3,
    price: 225,
  },
  {
    group: 'weapon',
    playerSide: 'ru',
    icon: 'fa-solid fa-radiation',
    name: 'РДС-4',
    description: 'Атомная бомба',
    tier: 3,
    price: 250,
  },
  // Пилот
  {
    group: 'pilot',
    icon: 'fa-solid fa-dumbbell',
    name: 'Выносливость',
    description: 'Устойчивость к перегрузкам',
    tier: 1,
    price: 50,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-eyes',
    name: 'Реакция',
    description: '',
    tier: 1,
    price: 75,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-head-side-gear',
    name: 'Шестое чувство',
    description:
      'Автопилот на столкновения, невозможность разбиться при посадке',
    tier: 1,
    price: 100,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-map-location-dot',
    name: 'Осведомленность',
    description:
      'Перед выполнением миссии более подробная карта с расположением вражеских целей',
    tier: 2,
    price: 125,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-clover',
    name: 'Везение',
    description: 'В первую очередь будут выпадать более дорогие улучшения',
    tier: 2,
    price: 150,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-graduation-cap',
    name: 'Скорость обучения',
    description: 'Коэффициент начисляемых очков x1.5',
    tier: 2,
    price: 175,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-person-military-rifle',
    name: 'Обмен',
    description:
      'Возможность продолжить игру при катапультировании над территорией противника',
    tier: 3,
    price: 200,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-brain',
    name: 'Интеллект',
    description: 'Возможность выбрать по завершению миссии 2 улучшения из 3',
    tier: 3,
    price: 225,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-angel',
    name: 'Второй шанс',
    description: 'Возможность переиграть миссию при смерти (1 раз на всю игру)',
    tier: 3,
    price: 250,
  },
];
