import { Upgrade } from '../upgrade/upgrade.model';

export const UPGRADES: Upgrade[] = [
  // Самолет
  {
    group: 'plane',
    icon: 'fa-solid fa-shuttle-space', // fa-solid fa-plane
    name: 'Планер',
    description: '',
    tier: 1,
    price: 50,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-plane-arrival',
    name: 'Автопилот',
    description: '',
    tier: 1,
    price: 75,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-weight-hanging',
    name: 'Конструкция',
    description: '',
    tier: 1,
    price: 100,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-paint-roller', // fa-solid fa-droplet
    name: 'Покрытие',
    description: '',
    tier: 2,
    price: 125,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-display',
    name: 'Кабина',
    description: '',
    tier: 2,
    price: 150,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-sitemap',
    name: 'Компоновка внутренних отсеков',
    description: '',
    tier: 2,
    price: 175,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-fire-flame-simple', // fa-solid fa-plane-engines
    name: 'Двигатели',
    description: '',
    tier: 3,
    price: 200,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-radar',
    name: 'РЛС',
    description: '',
    tier: 3,
    price: 225,
  },
  {
    group: 'plane',
    icon: 'fa-solid fa-satellite',
    name: 'ДРЛО',
    description: '',
    tier: 3,
    price: 250,
  },
  // Вооружение
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-volcano',
    name: 'M61 Vulcan',
    description: '',
    tier: 1,
    price: 50,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-bomb',
    name: 'Mark 83',
    description: '',
    tier: 1,
    price: 75,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-wind',
    name: 'AIM-9 Sidewinder',
    description: '',
    tier: 1,
    price: 100,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-person-walking',
    name: 'AGM-65 Maverick',
    description: '',
    tier: 2,
    price: 125,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-bird', // fa-dove
    name: 'AIM-7 Sparrow',
    description: '',
    tier: 2,
    price: 150,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-water',
    name: 'AGM-84 Harpoon',
    description: '',
    tier: 2,
    price: 175,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-brands fa-phoenix-framework',
    name: 'AIM-54 Phoenix',
    description: '',
    tier: 3,
    price: 200,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-satellite-dish',
    name: 'AGM-88 HARM',
    description: '',
    tier: 3,
    price: 225,
  },
  {
    group: 'weapon',
    playerSide: 'us',
    icon: 'fa-solid fa-radiation',
    name: 'B83',
    description: '',
    tier: 3,
    price: 250,
  },
  // Пилот
  {
    group: 'pilot',
    icon: 'fa-solid fa-dumbbell',
    name: 'Выносливость',
    description: '',
    tier: 1,
    price: 50,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-eyes',
    name: 'Реакция',
    description: '',
    tier: 1,
    price: 75,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-head-side-gear',
    name: 'Шестое чувство',
    description: '',
    tier: 1,
    price: 100,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-map-location-dot',
    name: 'Осведомленность',
    description: '',
    tier: 2,
    price: 125,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-clover',
    name: 'Везение',
    description: '',
    tier: 2,
    price: 150,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-graduation-cap',
    name: 'Скорость обучения',
    description: '',
    tier: 2,
    price: 175,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-person-military-rifle',
    name: 'Обмен',
    description: '',
    tier: 3,
    price: 200,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-brain',
    name: 'Интеллект',
    description: '',
    tier: 3,
    price: 225,
  },
  {
    group: 'pilot',
    icon: 'fa-solid fa-angel',
    name: 'Второй шанс',
    description: '',
    tier: 3,
    price: 250,
  },
];
